/*
 * qiangungun.com Inc.
 * Copyright (c) 2014 All Rights Reserved.
 */package com.qiangungun.monitor.dal.dataobject;

// auto generated imports
import java.util.Date;

/**
 * A data object class directly models database table <tt>compute_formula</tt>.
 *
 * This file is generated by <tt>financenet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/compute_formula.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>financenet-dalgen</tt> 
 * to generate this file.
 *
 */
public class ComputeFormulaDO {
    
    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private int id;

	/**
	 * This property corresponds to db column <tt>file_id</tt>.
	 */
	private String fileId;

	/**
	 * This property corresponds to db column <tt>compute_id</tt>.
	 */
	private String computeId;

	/**
	 * This property corresponds to db column <tt>compute_name</tt>.
	 */
	private String computeName;

	/**
	 * This property corresponds to db column <tt>formula_type</tt>.
	 */
	private String formulaType;

	/**
	 * This property corresponds to db column <tt>field_position</tt>.
	 */
	private String fieldPosition;

	/**
	 * This property corresponds to db column <tt>filter_condition</tt>.
	 */
	private String filterCondition;

	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.
	 */
	private Date gmtModified;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>id</tt>.
     *
     * @return property value of id
     */
	public int getId() {
		return id;
	}
	
	/**
	 * Setter method for property <tt>id</tt>.
	 * 
	 * @param id value to be assigned to property id
     */
	public void setId(int id) {
		this.id = id;
	}

    /**
     * Getter method for property <tt>fileId</tt>.
     *
     * @return property value of fileId
     */
	public String getFileId() {
		return fileId;
	}
	
	/**
	 * Setter method for property <tt>fileId</tt>.
	 * 
	 * @param fileId value to be assigned to property fileId
     */
	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

    /**
     * Getter method for property <tt>computeId</tt>.
     *
     * @return property value of computeId
     */
	public String getComputeId() {
		return computeId;
	}
	
	/**
	 * Setter method for property <tt>computeId</tt>.
	 * 
	 * @param computeId value to be assigned to property computeId
     */
	public void setComputeId(String computeId) {
		this.computeId = computeId;
	}

    /**
     * Getter method for property <tt>computeName</tt>.
     *
     * @return property value of computeName
     */
	public String getComputeName() {
		return computeName;
	}
	
	/**
	 * Setter method for property <tt>computeName</tt>.
	 * 
	 * @param computeName value to be assigned to property computeName
     */
	public void setComputeName(String computeName) {
		this.computeName = computeName;
	}

    /**
     * Getter method for property <tt>formulaType</tt>.
     *
     * @return property value of formulaType
     */
	public String getFormulaType() {
		return formulaType;
	}
	
	/**
	 * Setter method for property <tt>formulaType</tt>.
	 * 
	 * @param formulaType value to be assigned to property formulaType
     */
	public void setFormulaType(String formulaType) {
		this.formulaType = formulaType;
	}

    /**
     * Getter method for property <tt>fieldPosition</tt>.
     *
     * @return property value of fieldPosition
     */
	public String getFieldPosition() {
		return fieldPosition;
	}
	
	/**
	 * Setter method for property <tt>fieldPosition</tt>.
	 * 
	 * @param fieldPosition value to be assigned to property fieldPosition
     */
	public void setFieldPosition(String fieldPosition) {
		this.fieldPosition = fieldPosition;
	}

    /**
     * Getter method for property <tt>filterCondition</tt>.
     *
     * @return property value of filterCondition
     */
	public String getFilterCondition() {
		return filterCondition;
	}
	
	/**
	 * Setter method for property <tt>filterCondition</tt>.
	 * 
	 * @param filterCondition value to be assigned to property filterCondition
     */
	public void setFilterCondition(String filterCondition) {
		this.filterCondition = filterCondition;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}
