/*
 * qiangungun.com Inc.
 * Copyright (c) 2014 All Rights Reserved.
 */package com.qiangungun.monitor.dal.daointerface;

// auto generated imports
import com.qiangungun.monitor.dal.dataobject.ComputeFormulaDO;

import java.util.List;

import org.springframework.dao.DataAccessException;


/**
 * A dao interface provides methods to access database table <tt>compute_formula</tt>.
 *
 * This file is generated by <tt>financenet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/compute_formula.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>financenet-dalgen</tt> 
 * to generate this file.
 *
 */
public interface ComputeFormulaDAO {

	/**
	 *  Query DB table <tt>compute_formula</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, compute_id, compute_name, file_id, formula_type, field_position, filter_condition, gmt_create, gmt_modified from compute_formula</tt>
	 *
	 *	@return List<ComputeFormulaDO>
	 *	@throws DataAccessException
	 */	 
    public List<ComputeFormulaDO> getAll() throws DataAccessException;


	/**
	 *  Query DB table <tt>compute_formula</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, compute_id, compute_name, file_id, formula_type, field_position, filter_condition, gmt_create, gmt_modified from compute_formula where (file_id = ?)</tt>
	 *
	 *	@param fileId
	 *	@return List<ComputeFormulaDO>
	 *	@throws DataAccessException
	 */	 
    public List<ComputeFormulaDO> getByFileId(String fileId) throws DataAccessException;


	/**
	 *  Insert one <tt>ComputeFormulaDO</tt> object to DB table <tt>compute_formula</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into compute_formula(compute_id,compute_name,file_id,formula_type,field_position,filter_condition,gmt_create,gmt_modified) values (?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param computeFormula
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int insert(ComputeFormulaDO computeFormula) throws DataAccessException;


	/**
	 *  Update DB table <tt>compute_formula</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update compute_formula set compute_name=?, formula_type=?, field_position=?, filter_condition=? where (compute_id = ?)</tt>
	 *
	 *	@param computeName
	 *	@param formulaType
	 *	@param fieldPosition
	 *	@param filterCondition
	 *	@param computeId
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(String computeName, String formulaType, String fieldPosition, String filterCondition, String computeId) throws DataAccessException;

}